### ISSUE TITLE
Feature Request: Less Visible Buttons

### ISSUE THREAD

**Issue by MrPrimate** [ggagnon76/scene-scroller-maker#11]
I would like the Buttons to be hidden more in regular use. Could the buttons be placed under their own top-level button on the left rather than being visible all the time?

**Comment by ggagnon76** [comment]
I'm open to discuss this:

My reasoning for using the Lib-DF-Buttons module, which creates a separate dockable set of buttons, are:

1. This module is intended to be for prep work, not live games.
2. You can just turn the module on/off as needed
3. I dislike adding to core's UI buttons.  Some modules go overboard and when there are a lot of modules active, those UI buttons can overflow and become duplicates (icon images).

**Comment by ggagnon76** [comment]
Was thinking...

I can provide a client side setting that disables the buttons so they don't show.  In their place, the user would have to right click on the scene and access options there?

**Comment by MrPrimate** [comment]
This would work for me.

**Comment by ggagnon76** [comment]
I have implemented this in my dev branch.  It works nice and keeps the buttons from appearing on your player's clients too.

However, it requires a bug fix from the lib-df-buttons module, which I am waiting for.

**Comment by ggagnon76** [comment]
This has been implemented in v2.5.
