### ISSUE TITLE
Feature Request: Compendium Selection

### ISSUE THREAD

**Issue by MrPrimate** [ggagnon76/scene-scroller-maker#12]
I would like to either be able to select a compendium from a drop down (for an existing one) or for the module to remember a default one, rather than having to type the name each time.

**Comment by ggagnon76** [comment]
I can make a client side setting for this.

**Comment by ggagnon76** [comment]
This issue, which specifically targets 'divide a scene' functionality should be resolved with the release of v2.0.
It is now possible to select a default compendium in module settings, and this default is provided as an option in the 'divide a scene' UI.

**Comment by MrPrimate** [comment]
Thank you!
