### ISSUE TITLE
Feature Request: Remember Save Location

### ISSUE THREAD

**Issue by MrPrimate** [ggagnon76/scene-scroller-maker#13]
I would like to specify a default location to save images to.

**Comment by ggagnon76** [comment]
I can make a client side setting for this.

**Comment by ggagnon76** [comment]
This issue is partially resolved (divide a scene tool) with the creation of a default image folder in module settings.
V2.0 introduces this optional default to the 'divide a scene' tool, as an option in the UI.
The next release will propagate this option to all the other image tools.
