### ISSUE TITLE
Feature Request: Scene Division save to World rather than Compendium

### ISSUE THREAD

**Issue by MrPrimate** [ggagnon76/scene-scroller-maker#14]
I would like to be able to quickly create a new scene from a larger one into the world, rather than having to step through the process of importing it from a compendium after creation.

**Comment by ggagnon76** [comment]
I had to do this very thing for one of my own scenes.  I can see how this would be a convenience, and I do agree it should be an option.

However, I'll probably have to refactor the code quite a bit, as the code to save to a compendium is buried everywhere.  This one might take a while to implement.

**Comment by ggagnon76** [comment]
This issue should be resolved with the release of V2.0
The 'divide a scene' UI provides an option to create the scenes in the standard Scene Folder.

**Comment by MrPrimate** [comment]
Thank you!
