### ISSUE TITLE
Feature Request: Divide Into Smaller Scenes using drawing tools

### ISSUE THREAD

**Issue by MrPrimate** [ggagnon76/scene-scroller-maker#15]
I would like to be able to create a single cropped scene using the drawing tools rather than the fog of war.

e.g. a combination of the "Crop an Image" and "Divide a scene" options

**Comment by ggagnon76** [comment]
I think this would be difficult to implement.  The logic that figures out what walls (and other placeables) to keep would probably choke when walls can be half in and half out of the cropped area.

It would be a cool option, but I think I would have to re-write the 'culling' code to make it happen.  Not something that would happen anytime soon.

**Comment by ggagnon76** [comment]
Unless there is a big demand for this kind of feature, or I run out of ideas for other modules, I don't anticipate taking on this challenge.  Closing Issue.
