### ISSUE TITLE
Feature Request: Progamatic Access

### ISSUE THREAD

**Issue by MrPrimate** [ggagnon76/scene-scroller-maker#16]
I would like to be able to provide a scene and bounds to split up a scene programmatically.

Use case:
- I would like to maintain a list of splits for a scene, that if a user has one, can split it into smaller scenes. They could right click on the scene and select the option to split it.
- Ideally, these could be created into the world or a compendium.

**Comment by ggagnon76** [comment]
Would you want the module to provide the tools to create and embed the polygon coordinates to do this?
Similar to how the split selection works currently, but instead the data gets saved and if the user wants to split the big scene, the algorithm proceeds from where it left off?

**Comment by ggagnon76** [comment]
Released a potential solution for this via release v2.2.2:
- The data for the divisions are saved to scene flags (one of the options).
- The next time the divide-a-scene tool is initiated, you'll have the opportunity to load that data from flags and continue where you left off.

Does this feature let you achieve what you requested?

**Comment by MrPrimate** [comment]
I'll take a look over the weekend and get back to you, thanks

**Comment by MrPrimate** [comment]
This looks pretty good - is there a way I could trigger the scene division with an API call and suppress the dialogue/provide my own storage locations?

**Comment by ggagnon76** [comment]
If I had an idea of your end goal, it might help to get this right the first time.  Can discuss in private messages in Discord if you want to keep things private.

I can expose the method/function that runs the algorithm to divide the scene.  However, I don't fully understand what you mean by 'provide my own storage locations'.  Do you mean you want to store the polygon info that is used to divide the scene (what I've saved into the scene flags), or do you want to provide info on where to save the images/scenes like the default locations I've added to settings?

**Comment by MrPrimate** [comment]
Concept:

I have a bunch of scenes that have been imported, that have the division data stored in the flags. I'd like to be able to run the divide-a-scene process as part of a tool to break up a bunch of scenes. In addition to this, I would like to be able to specify where the images are stored when the scene is split up without overriding the module settings.

**Comment by ggagnon76** [comment]
So to be clear, you want to provide a destination for the images, that can be different from where the scene images already are, or from the default location defined in settings?  

What about the scenes themselves?  You want them saved in the scene folder or a compendium?

**Comment by MrPrimate** [comment]
> you want to provide a destination for the images, that can be different from where the scene images already are, or from the default location defined in settings?

Yes please!

>What about the scenes themselves? You want them saved in the scene folder or a compendium?

Hmm, an option for either would be nice, but would settle for a folder :)

**Comment by ggagnon76** [comment]
See new release v2.3.1

**Comment by MrPrimate** [comment]
Wonderful! Once final request - would it be possible to add an option to pass a folder or folderId  through to `processFlaggedDivisionData`? i.e. can I specify a folder in my world to save the scenes too?

**Comment by ggagnon76** [comment]
I'll have to look into Foundry's API to figure out how to do that.  I'll work on it, but no promises when.

**Comment by ggagnon76** [comment]
Check out release v2.4
