### ISSUE TITLE
[Bug] Module partially changes default font to Times New Roman

### ISSUE THREAD

**Issue by SirMotte** [ggagnon76/scene-scroller-maker#20]
Hey there, Scene Scroller Maker seems to overwrite the font style for portions of the UI with the Times New Roman Font. This is probably undesirable. Please see attached screenshots. If you need more information please don't hesitate to ask.

Tested on a fresh world with no other modules, but the dependency (and Module Management+, but this has no impact on the issue) installed (the dependency by itself does not cause this issue).

Could you look into this?

Also: Thank you so much for this incredibly useful tool!

![grafik](https://user-images.githubusercontent.com/82598692/195147685-74ea4918-5ab6-4e6f-bead-e7ae528427f6.png)
![grafik](https://user-images.githubusercontent.com/82598692/195147717-82b861c5-8953-4cb3-ba41-195bace46363.png)
![grafik](https://user-images.githubusercontent.com/82598692/195147743-e6e7905e-6ce1-4870-b8e6-f1ad58671ff6.png)

**Comment by ggagnon76** [comment]
I have been working on some new requested features and I know exactly what the problem is because I saw the CSS and thought to myself 'this is too generic'.  I will for sure have this fixed when I release the next version.

**Comment by SirMotte** [comment]
> I have been working on some new requested features and I know exactly what the problem is because I saw the CSS and thought to myself 'this is too generic'. I will for sure have this fixed when I release the next version.

Glad to hear this, thanks a lot. Might I suggest to not alter font settings at all? This way other modules that tie into this, like Ernie's Modern UI, could resume to do their magic beside your incredible module.

**Comment by ggagnon76** [comment]
It's CSS for paragraphs in my UI.  I just made the CSS too generic and it's changing ALL paragraphs in ALL forms.  That is an oversight and entirely my fault.  I do not intend to change fonts or any settings for any other module or system.  It is a very simple fix and not something I should have released in the first place.

**Comment by ggagnon76** [comment]
I released V2.0.  It should fix the CSS issue you are experiencing.  If it doesn't, let me know ASAP.

**Comment by SirMotte** [comment]
I can confirm, that the issue is fixed. Thanks a lot!
