### ISSUE TITLE
[Possible Bug]Image conversion fails, if image width and/or height exeeds a certain value.

### ISSUE THREAD

**Issue by SirMotte** [ggagnon76/scene-scroller-maker#21]
Issue:
If an image has very large proportions, for example 9918x19836px, conversion to webp fails, creating a 0bytes.webp file. I've dug a little around the net and tools like imagemagick suffer from the same behaviour, unless some settings are adjusted.

I haven't been able to pinpoint a definitive px value after which conversion fails.

If you could look into this, it'd be highly appreciated, I love to do everything I need for world-building within foundry.
Since you leverage the built in converter, this might be out of scope for you, feel free to close the issue if this is the case.

**Comment by ggagnon76** [comment]
I googled this and came across an article about max canvas size for various browsers:
https://stackoverflow.com/questions/6081483/maximum-size-of-a-canvas-element

Each browser has 2 limitations:
- width/height maximum
- area maximum

I have also read that the PC imposes its own limitations too.

It looks like this is a problem that has many variables...

Question:  Does that 10k x 20k image open in Foundry?

**Comment by SirMotte** [comment]
> I googled this and came across an article about max canvas size for various browsers: https://stackoverflow.com/questions/6081483/maximum-size-of-a-canvas-element
> 
> Each browser has 2 limitations:
> 
>     * width/height maximum
> 
>     * area maximum
> 
> 
> I have also read that the PC imposes its own limitations too.
> 
> It looks like this is a problem that has many variables...
> 
> Question: Does that 10k x 20k image open in Foundry?

I can mostly rule out browser interference, as the same issue happens with different conversion tools outside of Foundry as well.
Foundry is capable of rendering very large images, with increased file size, loading times increase as well obviously. The largest file I have in use in Foundry is my custom world map at 14000 x 12000px in the .png format. Loading locally takes approximately ~5 seconds on a SSD.

That being said, the file in question indeed **doesn't** load within Foundry at all. Bummer! I hadn't yet tested import of large files like that. If this is related to the converting issue I still think, this is unrelated to the browser aspect but a more basic codec issue.

The file itself can be opened with your average image viewer normally.

I will try to dig a little deeper and present you my findings. Thank you for your incredibly fast response!

**Comment by ggagnon76** [comment]
What I was trying to get across is maximum image size depends on browser and hardware.  What works for you, may not work for someone on a different browser with lesser hardware.

I just utilize the tools available in the PIXI JS API to change the format.  Foundry VTT uses PIXI JS to display images on their "canvas".  If Foundry can't open it (because of PIXI JS limitations), then my tooling won't be able to either.

The most I can try to do is to determine if loading a texture failed, if that is possible.  Needless to say, I think it now goes without saying that if a texture won't open in Foundry, my module won't be able to handle it either.

**Comment by SirMotte** [comment]
> What I was trying to get across is maximum image size depends on browser and hardware. What works for you, may not work for someone on a different browser with lesser hardware.
> 
> I just utilize the tools available in the PIXI JS API to change the format. Foundry VTT uses PIXI JS to display images on their "canvas". If Foundry can't open it (because of PIXI JS limitations), then my tooling won't be able to either.
> 
> The most I can try to do is to determine if loading a texture failed, if that is possible. Needless to say, I think it now goes without saying that if a texture won't open in Foundry, my module won't be able to handle it either.

Gotcha. Let me rule out that the images in question are simply broken from the get go, as converting my world map using your tool just now worked perfectly fine. I'll report back in a few.

**Comment by ggagnon76** [comment]
If you there is no problem with my module, feel free to close this issue.

**Comment by SirMotte** [comment]
To test this further, I created an single color value image with the same dimensions of 9918x19836px and this fails to both view and convert within foundry. The world map file at 14000x12000px does work however for conversion and viewing within foundry, and conversion outside of foundry using other tools.

Therefore I can rule out, that the module itself has an issue, and another underlying mechanic is at fault, possibly with some imposed restrictions on dimensions.

Sorry for jumping the gun here before properly testing the more obvious things, I was so focused on the dimension issue, that I kinda had tunnel vision there.

That being said, if you have a way to send some coffee your way, I do have some here, hot with sugar and milk if you like :). (I'd like to donate some cash hint hint).

**Comment by ggagnon76** [comment]
I think I've read in the #media-and-assets channel of Foundry Discord that the best graphics cards only accept images with a maximum pixel count of 18k on a side.

**Comment by SirMotte** [comment]
> I think I've read in the #media-and-assets channel of Foundry Discord that the best graphics cards only accept images with a maximum pixel count of 18k on a side.

Within the foundry environment or in general? Opening image files above 18k is possible on my rig (Geforce RTX 2080) outside of foundry. Also, in case you want to continue the conversion on discord, just pm me Sir Motte#1305. In case I can shed some light on the issue I will tell you asap. Though this has nothing to do with the module anymore :).


Edit: For anyone reading this. There is a dimension limit of 16383x16383px built into webp, that can't be exceeded.
Also different browsers have different maximum rendering limits. Exceeding those will only render a black image within Foundry:
![grafik](https://user-images.githubusercontent.com/82598692/195917704-089a8424-d535-4105-9d0a-7ea89c5b7412.png)
