### ISSUE TITLE
Can't see the scene navigation bar Toggle option 

### ISSUE THREAD

**Issue by jendives2000** [ggagnon76/scene-scroller-maker#27]
First of all, thanks a lot for this module. It worked fine before I updated to v10 I think. I have tons of png to convert to webp and this module saved me tons of time. So really, thanks.

I have the latest version of Foundry - v10.291. 
I have the lib DF module v1.4.2 installed as well as the v2.5 scene scroller module. 

The libDF module doesn't appear in my list of module from the settings after I launched my world, but it is in the list of modules installed from the dashboard.

I have no options settings for both modules. 

So i am not sure if SSM is working properly or not, if it is, why I am not seeing the Toggle SSM option from the scene navigation bar. 

Thanks a lot for your help!

**Comment by ggagnon76** [comment]
I am not yet sure there is anything wrong with Scene Scroller Maker that needs to be investigated.

I don't really understand what you mean by, `The libDF module doesn't appear in my list of module from the settings after I launched my world`?

My first question:  Do you see **_any_** buttons my module needs to function?

One possible culprit:  The button is only available for the active scene (look for the bullseye symbol).  It won't show for a viewed scene.

**Comment by ggagnon76** [comment]
Can't reproduce.
