### ISSUE TITLE
Missing Percent-Encoding URI checks.

### ISSUE THREAD

**Issue by EndlesNights** [ggagnon76/scene-scroller-maker#8]
If a folder name contains any non alpha numeric values within it, the folder path will returned as invalid.
If a file name contains any non alpha numeric  within it, while it will convert properly (but it will get a new name!), the automatic scene replacement will fail.

Example the file path of `Large Swamp [60x80].jpg` was changed into `Large%20Swamp%20%5B60x80%5D`

If I had to guess, this is because you might be missing Percent-Encoding URI checks on your input paths. Using `decodeURIComponent(pathStringHere)` on the  input strings for for your folder/file paths will probable be all you need to do to fix this issue.

**Comment by ggagnon76** [comment]
Thank you for using the module!  I will look into this.
Always more to learn.

**Comment by ggagnon76** [comment]
Added `decodeURIComponent` to path and filename inputs.  Tested with a folder called `Test Folder [A]` and filename `GL GrandHuntersHouse Basement SpiderLair [27x22].jpg`
